### ISSUE TITLE
Разработать описание процесса постановки задач

### ISSUE THREAD

**Issue by roberqwerty** [IT-manager-playbook/playbook#9]
# Цель 
Рассмотреть популярные принципы постановки задач и объяснить, почему они такие 

# Описание 
Рассмотреть с разных сторон процесс постановки задач: разобраться почему это не так просто как кажется, разобраться где граница между слишком слабо описанной задачей и раздутой задачей, что же это за зверь такой DoR и DoD

# Критерии приемки
- Документ опубликован в git
- Документ отвечает на вопросы в описании
- Документ позволит новичку договориться с командой о базовых принципах постановки задача

**Comment by fduch2k** [comment]
@roberqwerty Я бы ка кто то так задачу сформулировал бы. Немного "отсебятины" добавил про US, но по структуре - как то так.

# Цель

Дать руководителям команд и всем интересующимся сводную информацию про методики постановки и валидации задач и критерии использования этих методик в разных ситуациях. 

# Описание

Составить документ с описанием существующих подходов для валидации и  постановки задач. Документ должен содержать следующие разделы:

* Минимально необходимые требования к созданию задач (SMART, "слабо описанная задача", "раздутая задача");
* Описание методик для валидации задач перед взятием в работу (DoR, INVEST, тестирование etc);
* User Story vs Задача. Что и когда выбрать?

# Критерии приемки

* Документ с именем `tasks.md` создан в корне репозитория;
* Формат документа: `markdown`;
* Документ соответствует описанию.

**Comment by fduch2k** [comment]
Закрыто PR #24
